// import "./attr";
import "./checked";
import "./component";
// import "./css";
// import "./disable";
// import "./enable";
import "./event";
// import "./for";
import "./if";
import "./input";
import "./interpolate";
// import "./else";
// import "./options";
import "./ref";
import "./slot";
// import "./style";
import "./text";
import "./value";
