import "./attr";
import "./checked";
import "./component";
import "./class";
// import "./disable";
// import "./enable";
// import "./else";
import "./event";
import "./for";
import "./if";
import "./input";
import "./interpolate";
import "./router";
import "./options";
import "./ref";
import "./link";
import "./slot";
import "./style";
import "./text";
import "./value";
